# Generated by Django 6.0.4 on 2026-04-23 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, max_length=50, null=True)),
                ('length_weeks', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekly_order', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('warmup_notes', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='plans.workoutplan')),
            ],
            options={
                'ordering': ['weekly_order'],
                'unique_together': {('plan', 'weekly_order')},
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField()),
                ('default_sets', models.IntegerField()),
                ('rep_range_min', models.IntegerField()),
                ('rep_range_max', models.IntegerField()),
                ('rest_seconds', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_exercises', to='exercises.exercise')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_exercises', to='plans.workoutunit')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
