# Generated by Django 6.0.4 on 2026-04-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('workout', 'exercise', 'set_number')},
        ),
    ]
